[project]
name = "mpipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "mediapipe>=0.10.14",
    "numpy>=2.1.3",
    "opencv-python>=4.10.0.84",
]
